#pragma once

#include <tracerConfig.h>

TRACER_FLOAT lerp(TRACER_FLOAT low, TRACER_FLOAT high, TRACER_FLOAT t);
TRACER_FLOAT bilerp(TRACER_FLOAT x1, TRACER_FLOAT x2, TRACER_FLOAT y1, TRACER_FLOAT y2, TRACER_FLOAT x, TRACER_FLOAT y);