#pragma once

#define TRACER_BUFFER_WIDTH 800
#define TRACER_BUFFER_HEIGHT 600

#define TRACER_THREADS 16

#define DEFAULT_COLOR GS(50)
#define COLOR_RANDOMIZATION 20
#define ERASE_PREVIOUS_FRAME 1

#define SKYBOX_COLOR FRGB(0.33, 0.64, 1.00)

#define FOV RADIANS(120.0)
#define TRACER_EXPOSURE 100.0

#define ATMO_PROBE_SPACING 0.5
#define REFLECTION_RECURSION_LIMIT 3
#define NEAR_CLIPPING_DISTANCE 0.0001
#define INDIRECT_LIGHTING 1
#define INDIRECT_LIGHTING_RECURSIONS 5

#define TRACER_FLOAT double
#define TRACER_TRIG_DOUBLE_PRECISION 1
#define RANDOM_VALUE_COUNT 1000000