#pragma once

#define TRACER_BUFFER_WIDTH 800
#define TRACER_BUFFER_HEIGHT 600

#define TRACER_THREADS 0
#define TRACER_PTHREAD_PRIORITIZE_THREADS 1

#define DEFAULT_COLOR GS(50)
#define COLOR_RANDOMIZATION 20

#define SKYBOX_COLOR FRGB(0.33, 0.64, 1.00)

#define FOV RADIANS(70.0)
#define TRACER_EXPOSURE 100.0
#define DYNAMIC_RANGE 0.0

#define REFLECTION_RECURSION_LIMIT 2
#define NEAR_CLIPPING_DISTANCE 0.0001
#define INDIRECT_LIGHTING 0
#define INDIRECT_LIGHTING_RECURSIONS 10

#define TRACER_FLOAT double
#define TRACER_TRIG_DOUBLE_PRECISION 1
#define RANDOM_VALUE_COUNT 1000000